apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-ip-nginx
  labels:
    env: dev
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-cluster
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 80
              name: http
    
