apiVersion: v1
kind: Service
metadata:
  name: nginx-cluster
  labels: 
    service: nginx-cluster-ip
    env: test
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    name: http
    targetPort: 80
  type: ClusterIP 
      
