apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  labels:
    service: nginx-nodeport
    env: test
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    name: nginx-nodeport
    targetPort: 80
    nodePort: 32000
  type: NodePort
