apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nginx-podmonitor
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  namespaceSelector:
    matchNames:
      - default
  podMetricsEndpoints:
    - interval: 10s
      path: metrics
      targetPort: 9113
     

