apiVersion: v1
kind: Service
metadata:
  name: website
  labels:
    app: nginx
    version: "1.0"
    env: prod
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http-nginx

