apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  labels:
    version: "1.0"
    env: prod
    app: website
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    name: nginx-nodeport
    targetPort: 80
    nodePort: 32100
  type: NodePort
