apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-set-cluster-ip
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx
  replicas: 4 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - name: website
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: website
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 500Mi
