apiVersion: v1
kind: Pod
metadata:
  name: with-secrets
spec:
  containers:
  - image: nginx
    name: nginx
    env:
    - name: USER
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: user
    - name: PASS
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: pass
    resources:
      requests:
        cpu: "100m"
        memory: "250Mi"
      limits:
        cpu: "200m"
        memory: "400Mi"